name: Android CI

on:
  push:
    branches: [ wip/actions ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.14.1

      - name: Build with Gradle
        # registration secrets is required:
        # - KEYSTORE_BASE64 (create release.keystore on your local and do `cat release.keystore | base64`)
        # - KEYSTORE_PASSWORD
        # - KEY_ALIAS
        # - KEY_PASSWORD
        #
        # * DON'T push keystore file for release to remote branch *
        run: |
          echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > release.keystore
          export KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
          ./gradlew assembleProdRelease
      - name: Upload apk file as artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-prod-release
          path: app/build/outputs/apk/prod/release/app-prod-release.apk
      - name: Upload apk file to DeployGate
        uses: jmatsu/dg-upload-app-action@7d6f61a
        with:
          # registration secrets is required:
          # - DEPLOYGATE_APP_OWNER_NAME (not mail address)
          # - DEPLOYGATE_API_TOKEN
          app_owner_name: ${{ secrets.DEPLOYGATE_APP_OWNER_NAME }}
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: app/build/outputs/apk/prod/release/app-prod-release.apk
